### PR TITLE
Added privilege dropping and default/custom umask

### PR DESCRIPTION
**Pull request by mzpqnxow**
Hello,

I like using your project in a pinch when I want to stand up the tftp portion of a PXE boot server, or need to transfer files to a tftpd from a network device. It's very useful, thank you for it. Most Linux distributions make you work very, very, hard to find and configure a tftp server that allows remote write requests.. ughh

Because many of the wacky network devices I use don't allow you specify a port, they require port 69, per the RFC and IANA. This is annoying to me as I don't want to `setcap` the python interpreter, I'm too lazy to set up a proper systemd entry, etc, etc. You get the point.

I chose this method for simplifying things, without giving up any potential security issues. You can run your tftpd as root, and it will drop privileges to a user/group that you choose. I also added umask support while I was at it. I tried my best to stick to your existing style and structure.

Interested in accepting this PR? Or should I just keep the fork to myself?

*NOTE*: I *very, very, very* much do not like the style of your code (and fie naming) though I don't mean it as an insult- I am just a very picky and pedantic person. The reason I say this is not to be an asshole, but to offer (if you ever have interest in a `tftpy2`) to help. As an example of what Pythonic/PEP "standards" think of your style, try `pycodestyle`, `pylint`, etc. on your codebase. I am sure with a chance to do it over it could be much simpler, and probably more performant (though I doubt anyone here, including me, cares about performance of tftp :)

I would also be happy to begin to contribute to or start a refactor or rewrite.

Thanks again, and please don't take my critical comments the wrong way! Please put a note in this PR if anything above sounds appealing.

### CODE REVIEW

**Comment by msoulier** [comment]
Hmm. I like it, although I don't see any test updates to exercise it. I would think that would be far more important than my code style. ;-)

**Comment by msoulier** [comment]
Immediate testcase failure. It's trying to shed privileges when I'm not even running as root.

`INFO [tftpy.TftpServer:91] Server requested on ip localhost, port 0
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/Cellar/python@2/2.7.15_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python@2/2.7.15_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Users/msoulier/work/tftpy/tftpy/TftpServer.py", line 101, in listen
    self.drop_privileges()
  File "/Users/msoulier/work/tftpy/tftpy/TftpServer.py", line 275, in drop_privileges
    raise RuntimeError('unable to drop privileges, must be root')
RuntimeError: unable to drop privileges, must be root`

**Comment by mzpqnxow** [comment]
Oops! I will take a look now. Apologies for not adding tests, I tend to be a little careless at times when it comes to performing thorough testing (or, what seems like basic testing here!)

**Comment by mzpqnxow** [comment]
@msoulier are you opposed to PEP8 style? I don't mean necessarily modifying all of the existing project to fit PEP8, but as I touch the 1-2 files I need to during fixing up this patch, are you OK with styling as PEP8 along the way?

**Comment by mzpqnxow** [comment]
I'm finishing up the updates to `test.py`, some changes need to be made since the file that is created isn't writable when the privilege-dropped tests run. However I reworked all of the actual code and tested it quite a bit to make sure this revision is more robust- though I'm not entirely happy with how clunky I made all of the sanity checking

**Comment by mzpqnxow** [comment]
@msoulier I think this is complete now. I added test cases for the privilege dropping. I also fixed a bug I came across in TftpStates where access denied when opening the requested file was not handled and resulted in a stack trace and the server bailing. While I was at it I added a catchall OSError handler along with it just for good measure

Also sorry for what I said about your code, I am just very obsessive about formatting- but this is not my project and it is very functional as well as readable, so I will try to calm myself :)

**Comment by mzpqnxow** [comment]
@msoulier are you still interested in accepting this PR? I forgot about it and have been using `pip install git+https://github.com/mzpqnxow/tftpy` to install the package directly. Feel free to accept or close this. Thanks!

**Comment by mzpqnxow** [comment]
Actually, better hold off on this, I think I mixed up a test case ... d'oh

**Pull request closed without merging**
