### PR TITLE
Adding python3 support

### PR DESCRIPTION
**Pull request by oriordan**
Had some initial testing, and it works fine, the rest is up for the community.

Made some changes in the behavior:
- the original logging mechanism is too verbose for general logs
- the dyn_file_func gets the raddress and rport via kwargs

### CODE REVIEW

**Comment by FlyingLotus1983** [comment]
@msoulier , any chance of merging this pull request in?  Would be really nice to get this into the official repo :+1:

**Comment by msoulier** [comment]
Need to go one better. This should be at the top of every file.

from __future__ import absolute_import, division, print_function, unicode_literals

**Comment by msoulier** [comment]
https://wiki.python.org/moin/PortingToPy3k/BilingualQuickRef

**Comment by msoulier** [comment]
I have all tests passing with my changes on top of these for python2. The tests are failing for python3, but I'm going to merge and then fix the problems.

**Pull request merged**
