### PR TITLE
Compatibility with Python 3.x

### PR DESCRIPTION
**Pull request by ZuljinSBK**
What was changed:
1) Modified setup.py to call 2to3 script. This will automatically introduce lots of Python 3 improvements during setup procedure.
2) Created to_bytes() and to_str() functions that will handle string conversion. These functions differ for both version of Python.
3) Changed internal representation of options value to int instead of string. AFAIK all TFTP options values are right now integers so this should work without any issue. I wanted integers because it is easier to handle them than strings in Python 2 and 3. Additionally lots of options value calculations are done using integers so this simplify some part of code.
4) Updated unittests to work with Python 3
5) Few small changes that increase compatibility between Python 2 and 3.

### CODE REVIEW

**Comment by msoulier** [comment]
Nothing wrong with the ideas here but maybe I messed up in the merge. Lots of failing testcases now under python2.

**Comment by anthraxx** [comment]
This should be revisited soon... i mean in 2020 python2 is EOL :yum:

**Comment by jaapcrezee** [comment]
Any work/word on getting things functional with python3?

**Comment by dotRollen** [comment]
Would like to hear if this is moving into Python 3. Would like to contribute if so.

**Comment by msoulier** [comment]
Trying to. Might need to cut compatibility with 2.7 though.

mps

**Comment by msoulier** [comment]
I am closing this as I hope to have a python3 branch working soon. Once all testcases are passing I will merge to master.

**Pull request closed without merging**
