### PR TITLE
IPv6 option

### PR DESCRIPTION
**Pull request by sanseihappa**
In reference to #71

### CODE REVIEW

**Comment by sanseihappa** [comment]
@msoulier Hi, I was wondering if you'd be willing to take the PR and roll a minor bump to the package in PyPI?

**Comment by sanseihappa** [comment]
@msoulier Any chance of rolling this change in?

**Comment by msoulier** [comment]
I can merge this in, but it seems like I'd need to do a lot more to fully support ipv6. Especially on the client.

**Comment by msoulier** [comment]
This patch isn't going to work. It allows the main listening socket for the server to be ipv6 but the session sockets are still hard-coded to ipv4. See line 78 of TftpContexts.py.

Lots more work to do to support ipv6. It's on my list.

**Pull request closed without merging**
